version: 2

defaults: &defaults
  docker:
    - image: node:10.3.0

jobs:
  install_dependencies_and_test:
    <<: *defaults
    steps:
      - restore_cache: &restore_src_cache
          keys:
            - v1-source-cache-{{ .Branch }}
            - v1-source-cache-
      - checkout
      - save_cache:
          key: v1-source-cache-{{ .Branch }}
          paths:
            - .git
      - restore_cache: &restore_node_modules
          keys:
            - v1-node_modules-{{ checksum "package-lock.json" }}
            - v1-node_modules-
      - run: npm ci
      - save_cache:
          key: v1-node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
      - store_test_results:
          path: coverage

  release_to_npm:
    <<: *defaults
    steps:
      - restore_cache: &restore_src_cache
          keys:
            - v1-source-cache-{{ .Branch }}
            - v1-source-cache-
      - checkout
      - restore_cache: &restore_node_modules
          keys:
            - v1-node_modules-{{ checksum "package-lock.json" }}
            - v1-node_modules-
      - run: npm ci
      - run: npm run semantic-release

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  continuous_integration:
    jobs:
      - install_dependencies_and_test
      - hold_release_to_npm:
          type: approval
          requires:
            - install_dependencies_and_test
          filters:
            branches:
              only: master
      - release_to_npm:
          requires:
            - hold_release_to_npm
      - hold_deploy:
          type: approval
          requires:
            - install_dependencies_and_test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold_deploy
